
const EErrors = {
    ERR_ROUTING: 1,
    ERR_INVALID_TYPES: 2,
    ERR_DATABASE: 3,
    ERR_SERVER: 4,
    ERR_PROPERTY_EMPTY: 5,
    ERR_PRODUCT_EXIST: 6,
    ERR_PRODUCT_NOT_FOUND: 7,
    ERR_PRODUCT_NOT_SAVE: 8,
    ERR_CART_NOT_FOUND: 9,
    ERR_CART_EMPTY: 10,
    ERR_CART_NOT_SAVE: 11
}

export default EErrors;